#!/bin/bash

includeIfExists "$HOME/.bash_colors"

function call_update_cmd() {
	
	printf "\n"

	if [ "$#" -eq "2" ];
		then
			printf "${_MAGENTA_BRIGHT_}Calling ${_CYAN_BRIGHT_}\"$1\" ${_MAGENTA_BRIGHT_}$2.\n\n${_DEFAULT_COLOR_}"
		else
			printf "${_MAGENTA_BRIGHT_}Calling ${_CYAN_BRIGHT_}\"$1\".\n\n${_DEFAULT_COLOR_}"
	fi
	
	$1
	
	printf "\n"
	printf "\n"

}

call_update_cmd "sudo apt update" "to update package database"
call_update_cmd "sudo apt upgrade" "to upgrade system packages"
call_update_cmd "sudo apt autoremove" "to remove unused packages. BE CAREFULL, DON'T AGREE TO THIS WILLY NILLY"
call_update_cmd "flatpak update" "to update your flatpaks"
call_update_cmd "flatpak uninstall --unused" "to clean up your flatpaks"
call_update_cmd "sudo snap refresh" "to update your snaps (EWWW ... just kidding I appreciate my snaps)"
call_update_cmd "rustup update" "to update rust and Cargo and such"

printf "\n${_BLUE_}Updateing nvm without your fancy function. Perhaps these curl updates need a fancy function of their own ...\n"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

call_update_cmd "exec $SHELL" "to update terminal session now that your updates have finished"
